use serde::{Deserialize, Serialize};
use std::collections::{BTreeMap, HashSet};
use std::fs;
use std::io;
use std::path::{Path, PathBuf};
use std::time::{SystemTime, UNIX_EPOCH};

const JSON_FILE_NAME: &str = "workspace-preferences.json";
const MARKDOWN_FILE_NAME: &str = "workspace-preferences.md";
const SCHEMA_VERSION: u8 = 1;
const RECENT_WORKSPACE_LIMIT: usize = 5;
const PROVIDERS: [(&str, &str); 4] = [
    ("hermes", "Hermes CLI"),
    ("codex", "Codex CLI"),
    ("claude", "Claude CLI"),
    ("antigravity", "Antigravity CLI"),
];

#[derive(Clone, Debug, Default, Deserialize, PartialEq, Eq, Serialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct WorkspacePreference {
    default_workspace: String,
    recent_workspaces: Vec<String>,
}

pub type WorkspacePreferences = BTreeMap<String, WorkspacePreference>;

#[derive(Debug, Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
struct WorkspacePreferencesFile {
    version: u8,
    providers: WorkspacePreferences,
}

#[derive(Debug, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct WorkspacePreferencesState {
    exists: bool,
    preferences: Option<WorkspacePreferences>,
}

#[derive(Debug, PartialEq, Eq, Serialize)]
pub struct StorageError {
    pub(crate) code: String,
    pub(crate) message: String,
    pub(crate) status_code: u16,
}

impl StorageError {
    fn new(code: &str, message: impl Into<String>) -> Self {
        Self {
            code: code.to_string(),
            message: message.into(),
            status_code: 500,
        }
    }
}

fn json_path(directory: &Path) -> PathBuf {
    directory.join(JSON_FILE_NAME)
}

fn markdown_path(directory: &Path) -> PathBuf {
    directory.join(MARKDOWN_FILE_NAME)
}

fn empty_preferences() -> WorkspacePreferences {
    PROVIDERS
        .iter()
        .map(|(id, _)| ((*id).to_string(), WorkspacePreference::default()))
        .collect()
}

fn normalize_preferences(input: WorkspacePreferences) -> WorkspacePreferences {
    let mut normalized = empty_preferences();
    for (provider_id, _) in PROVIDERS {
        let Some(preference) = input.get(provider_id) else {
            continue;
        };
        let mut seen = HashSet::new();
        let recent_workspaces = preference
            .recent_workspaces
            .iter()
            .filter(|path| !path.is_empty() && seen.insert((*path).clone()))
            .take(RECENT_WORKSPACE_LIMIT)
            .cloned()
            .collect();
        normalized.insert(
            provider_id.to_string(),
            WorkspacePreference {
                default_workspace: preference.default_workspace.clone(),
                recent_workspaces,
            },
        );
    }
    normalized
}

fn validate_file(file: &WorkspacePreferencesFile) -> bool {
    if file.version != SCHEMA_VERSION || file.providers.len() != PROVIDERS.len() {
        return false;
    }

    let expected: HashSet<&str> = PROVIDERS.iter().map(|(id, _)| *id).collect();
    if !file
        .providers
        .keys()
        .all(|provider_id| expected.contains(provider_id.as_str()))
    {
        return false;
    }

    file.providers.values().all(|preference| {
        preference.recent_workspaces.len() <= RECENT_WORKSPACE_LIMIT
            && preference
                .recent_workspaces
                .iter()
                .all(|path| !path.is_empty())
            && preference
                .recent_workspaces
                .iter()
                .collect::<HashSet<_>>()
                .len()
                == preference.recent_workspaces.len()
    })
}

fn markdown_value(value: &str) -> String {
    value.replace('\r', "\\r").replace('\n', "\\n")
}

fn render_markdown(preferences: &WorkspacePreferences) -> String {
    let mut markdown = String::from(
        "# AgentOS Console Workspace Preferences\n\n\
         Generated from `workspace-preferences.json`. Do not edit this file directly.\n",
    );

    for (provider_id, display_name) in PROVIDERS {
        let preference = preferences
            .get(provider_id)
            .expect("normalized preferences contain every provider");
        markdown.push_str(&format!("\n## {display_name}\n\n"));
        if preference.default_workspace.is_empty() {
            markdown.push_str("- Default Workspace: Not set\n");
        } else {
            markdown.push_str(&format!(
                "- Default Workspace: {}\n",
                markdown_value(&preference.default_workspace)
            ));
        }
        markdown.push_str("- Recent Workspaces:\n");
        if preference.recent_workspaces.is_empty() {
            markdown.push_str("  - None\n");
        } else {
            for workspace in &preference.recent_workspaces {
                markdown.push_str(&format!("  - {}\n", markdown_value(workspace)));
            }
        }
    }
    markdown
}

fn temporary_path(path: &Path, purpose: &str) -> PathBuf {
    let unique = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .unwrap_or_default()
        .as_nanos();
    let file_name = path
        .file_name()
        .and_then(|name| name.to_str())
        .unwrap_or("workspace-preferences");
    path.with_file_name(format!(
        ".{file_name}.{}-{unique}-{purpose}",
        std::process::id()
    ))
}

fn write_temporary(path: &Path, contents: &[u8]) -> io::Result<()> {
    use std::io::Write;

    let mut file = fs::OpenOptions::new()
        .create_new(true)
        .write(true)
        .open(path)?;
    file.write_all(contents)?;
    file.sync_all()
}

fn restore_file(path: &Path, previous: Option<&[u8]>) -> io::Result<()> {
    match previous {
        Some(contents) => {
            let rollback = temporary_path(path, "rollback");
            write_temporary(&rollback, contents)?;
            fs::rename(rollback, path)
        }
        None => match fs::remove_file(path) {
            Ok(()) => Ok(()),
            Err(error) if error.kind() == io::ErrorKind::NotFound => Ok(()),
            Err(error) => Err(error),
        },
    }
}

fn replace_pair_with<F>(
    json: &Path,
    markdown: &Path,
    json_temporary: &Path,
    markdown_temporary: &Path,
    previous_json: Option<&[u8]>,
    mut replace: F,
) -> io::Result<()>
where
    F: FnMut(&Path, &Path) -> io::Result<()>,
{
    replace(json_temporary, json)?;
    if let Err(error) = replace(markdown_temporary, markdown) {
        let _ = restore_file(json, previous_json);
        return Err(error);
    }
    Ok(())
}

fn write_pair(directory: &Path, preferences: &WorkspacePreferences) -> Result<(), StorageError> {
    let json = json_path(directory);
    let markdown = markdown_path(directory);
    fs::create_dir_all(directory).map_err(|_| {
        StorageError::new(
            "storage_unavailable",
            format!(
                "Workspace preferences directory could not be created at {}",
                directory.display()
            ),
        )
    })?;

    let file = WorkspacePreferencesFile {
        version: SCHEMA_VERSION,
        providers: preferences.clone(),
    };
    let mut json_contents = serde_json::to_vec_pretty(&file).map_err(|_| {
        StorageError::new(
            "storage_write_failed",
            format!(
                "Workspace preferences could not be saved at {}",
                json.display()
            ),
        )
    })?;
    json_contents.push(b'\n');
    let markdown_contents = render_markdown(preferences).into_bytes();

    let previous_json = if json.exists() {
        Some(fs::read(&json).map_err(|_| {
            StorageError::new(
                "storage_write_failed",
                format!(
                    "Workspace preferences could not be saved at {}",
                    json.display()
                ),
            )
        })?)
    } else {
        None
    };
    if markdown.exists() {
        fs::read(&markdown).map_err(|_| {
            StorageError::new(
                "storage_write_failed",
                format!(
                    "Workspace preferences summary could not be saved at {}",
                    markdown.display()
                ),
            )
        })?;
    }

    let json_temporary = temporary_path(&json, "pending");
    let markdown_temporary = temporary_path(&markdown, "pending");
    write_temporary(&json_temporary, &json_contents).map_err(|_| {
        StorageError::new(
            "storage_write_failed",
            format!(
                "Workspace preferences could not be saved at {}",
                json.display()
            ),
        )
    })?;
    if write_temporary(&markdown_temporary, &markdown_contents).is_err() {
        let _ = fs::remove_file(&json_temporary);
        return Err(StorageError::new(
            "storage_write_failed",
            format!(
                "Workspace preferences summary could not be saved at {}",
                markdown.display()
            ),
        ));
    }

    let replaced = replace_pair_with(
        &json,
        &markdown,
        &json_temporary,
        &markdown_temporary,
        previous_json.as_deref(),
        |from, to| fs::rename(from, to),
    );
    if replaced.is_err() {
        let _ = fs::remove_file(&json_temporary);
        let _ = fs::remove_file(&markdown_temporary);
        return Err(StorageError::new(
            "storage_write_failed",
            format!(
                "Workspace preferences could not be saved at {}",
                json.display()
            ),
        ));
    }
    Ok(())
}

fn ensure_markdown(
    directory: &Path,
    preferences: &WorkspacePreferences,
) -> Result<(), StorageError> {
    let markdown = markdown_path(directory);
    let expected = render_markdown(preferences);
    if fs::read_to_string(&markdown).ok().as_deref() == Some(expected.as_str()) {
        return Ok(());
    }

    let temporary = temporary_path(&markdown, "pending");
    write_temporary(&temporary, expected.as_bytes()).map_err(|_| {
        StorageError::new(
            "storage_write_failed",
            format!(
                "Workspace preferences summary could not be saved at {}",
                markdown.display()
            ),
        )
    })?;
    fs::rename(&temporary, &markdown).map_err(|_| {
        let _ = fs::remove_file(&temporary);
        StorageError::new(
            "storage_write_failed",
            format!(
                "Workspace preferences summary could not be saved at {}",
                markdown.display()
            ),
        )
    })
}

pub fn read_preferences(directory: &Path) -> Result<WorkspacePreferencesState, StorageError> {
    let json = json_path(directory);
    if !json.exists() {
        return Ok(WorkspacePreferencesState {
            exists: false,
            preferences: None,
        });
    }

    let contents = fs::read_to_string(&json).map_err(|_| {
        StorageError::new(
            "storage_read_failed",
            format!(
                "Workspace preferences could not be read at {}",
                json.display()
            ),
        )
    })?;
    let file: WorkspacePreferencesFile = serde_json::from_str(&contents).map_err(|_| {
        StorageError::new(
            "invalid_storage",
            format!(
                "Workspace preferences at {} are invalid. Fix, rename, or delete the file and press Refresh.",
                json.display()
            ),
        )
    })?;
    if !validate_file(&file) {
        return Err(StorageError::new(
            "invalid_storage",
            format!(
                "Workspace preferences at {} are invalid. Fix, rename, or delete the file and press Refresh.",
                json.display()
            ),
        ));
    }
    ensure_markdown(directory, &file.providers)?;
    Ok(WorkspacePreferencesState {
        exists: true,
        preferences: Some(file.providers),
    })
}

pub fn initialize_preferences(
    directory: &Path,
    preferences: WorkspacePreferences,
) -> Result<WorkspacePreferences, StorageError> {
    if json_path(directory).exists() {
        return read_preferences(directory)?.preferences.ok_or_else(|| {
            StorageError::new(
                "storage_read_failed",
                "Workspace preferences could not be loaded",
            )
        });
    }
    let normalized = normalize_preferences(preferences);
    write_pair(directory, &normalized)?;
    Ok(normalized)
}

pub fn write_preferences(
    directory: &Path,
    preferences: WorkspacePreferences,
) -> Result<WorkspacePreferences, StorageError> {
    if !json_path(directory).exists() {
        return Err(StorageError::new(
            "storage_not_initialized",
            format!(
                "Workspace preferences are not initialized at {}",
                json_path(directory).display()
            ),
        ));
    }
    read_preferences(directory)?;
    let normalized = normalize_preferences(preferences);
    write_pair(directory, &normalized)?;
    Ok(normalized)
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::sync::atomic::{AtomicU64, Ordering};

    static NEXT_TEMP_ID: AtomicU64 = AtomicU64::new(0);

    fn temp_directory() -> PathBuf {
        let sequence = NEXT_TEMP_ID.fetch_add(1, Ordering::Relaxed);
        let directory =
            std::env::temp_dir().join(format!("agentos-storage-{}-{sequence}", std::process::id()));
        fs::create_dir(&directory).unwrap();
        directory
    }

    fn sample_preferences() -> WorkspacePreferences {
        BTreeMap::from([(
            "codex".to_string(),
            WorkspacePreference {
                default_workspace: "/default".to_string(),
                recent_workspaces: vec![
                    "/one".to_string(),
                    "/one".to_string(),
                    "/two".to_string(),
                    "/three".to_string(),
                    "/four".to_string(),
                    "/five".to_string(),
                    "/six".to_string(),
                ],
            },
        )])
    }

    #[test]
    fn initializes_fixed_schema_and_markdown_order() {
        let directory = temp_directory();

        let preferences = initialize_preferences(&directory, BTreeMap::new()).unwrap();
        let json = fs::read_to_string(json_path(&directory)).unwrap();
        let markdown = fs::read_to_string(markdown_path(&directory)).unwrap();

        assert_eq!(preferences.len(), 4);
        assert!(json.contains("\"version\": 1"));
        let positions = PROVIDERS.map(|(_, name)| markdown.find(name).unwrap());
        assert!(positions.windows(2).all(|pair| pair[0] < pair[1]));
        assert_eq!(markdown.matches("Default Workspace: Not set").count(), 4);
        assert_eq!(markdown.matches("  - None").count(), 4);
        fs::remove_dir_all(directory).unwrap();
    }

    #[test]
    fn normalizes_migration_to_fixed_providers_and_five_unique_recent_paths() {
        let directory = temp_directory();

        let preferences = initialize_preferences(&directory, sample_preferences()).unwrap();

        assert_eq!(
            preferences["codex"].recent_workspaces,
            ["/one", "/two", "/three", "/four", "/five"]
        );
        assert!(preferences["hermes"].default_workspace.is_empty());
        fs::remove_dir_all(directory).unwrap();
    }

    #[test]
    fn existing_json_is_authoritative_during_initialization() {
        let directory = temp_directory();
        let existing = initialize_preferences(&directory, sample_preferences()).unwrap();
        let replacement = BTreeMap::from([(
            "codex".to_string(),
            WorkspacePreference {
                default_workspace: "/replacement".to_string(),
                recent_workspaces: vec![],
            },
        )]);

        let loaded = initialize_preferences(&directory, replacement).unwrap();

        assert_eq!(loaded, existing);
        fs::remove_dir_all(directory).unwrap();
    }

    #[test]
    fn invalid_json_is_preserved_and_reports_its_full_path() {
        let directory = temp_directory();
        let json = json_path(&directory);
        fs::write(&json, "{ invalid").unwrap();

        let error = read_preferences(&directory).unwrap_err();

        assert_eq!(error.code, "invalid_storage");
        assert!(error.message.contains(&json.to_string_lossy().into_owned()));
        assert_eq!(fs::read_to_string(json).unwrap(), "{ invalid");
        fs::remove_dir_all(directory).unwrap();
    }

    #[test]
    fn write_does_not_overwrite_json_that_became_invalid_after_loading() {
        let directory = temp_directory();
        initialize_preferences(&directory, sample_preferences()).unwrap();
        let json = json_path(&directory);
        fs::write(&json, "{ changed externally").unwrap();

        let error = write_preferences(&directory, sample_preferences()).unwrap_err();

        assert_eq!(error.code, "invalid_storage");
        assert_eq!(fs::read_to_string(json).unwrap(), "{ changed externally");
        fs::remove_dir_all(directory).unwrap();
    }

    #[test]
    fn missing_or_edited_markdown_is_regenerated_from_json() {
        let directory = temp_directory();
        initialize_preferences(&directory, sample_preferences()).unwrap();
        fs::write(markdown_path(&directory), "manual edit").unwrap();

        read_preferences(&directory).unwrap();

        let markdown = fs::read_to_string(markdown_path(&directory)).unwrap();
        assert!(markdown.contains("Generated from `workspace-preferences.json`"));
        assert!(!markdown.contains("manual edit"));
        fs::remove_dir_all(directory).unwrap();
    }

    #[test]
    fn failed_summary_replace_restores_previous_json() {
        let directory = temp_directory();
        let json = json_path(&directory);
        let markdown = markdown_path(&directory);
        fs::write(&json, b"old-json").unwrap();
        fs::write(&markdown, b"old-markdown").unwrap();
        let next_json = directory.join("next-json");
        let next_markdown = directory.join("next-markdown");
        fs::write(&next_json, b"new-json").unwrap();
        fs::write(&next_markdown, b"new-markdown").unwrap();
        let mut replacements = 0;

        let result = replace_pair_with(
            &json,
            &markdown,
            &next_json,
            &next_markdown,
            Some(b"old-json"),
            |from, to| {
                replacements += 1;
                if replacements == 2 {
                    Err(io::Error::other("simulated failure"))
                } else {
                    fs::rename(from, to)
                }
            },
        );

        assert!(result.is_err());
        assert_eq!(fs::read(&json).unwrap(), b"old-json");
        assert_eq!(fs::read(&markdown).unwrap(), b"old-markdown");
        fs::remove_dir_all(directory).unwrap();
    }

    #[test]
    fn saved_missing_workspaces_are_not_pruned() {
        let directory = temp_directory();
        let preferences = initialize_preferences(&directory, sample_preferences()).unwrap();

        let loaded = read_preferences(&directory).unwrap().preferences.unwrap();

        assert_eq!(loaded, preferences);
        assert!(loaded["codex"]
            .recent_workspaces
            .contains(&"/one".to_string()));
        fs::remove_dir_all(directory).unwrap();
    }
}
